import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import { SuperDataProvider } from "@/components/superDataProvider";

const universalSans = localFont({
  src: "../public/UniversalSansGX-Medium (1).ttf",
  variable: "--font-universal-sans",
  display: "swap",
});

const polySansBrand = localFont({
  src: "../public/PolySans-Neutral.otf",
  variable: "--font-poly-sans-brand",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${universalSans.variable} ${polySansBrand.variable} antialiased`}>
        <SuperDataProvider>
          <Header />
          <div className="h-full w-full max-w-4xl mx-auto flex flex-col items-center justify-center px-4 py-16">
          {children}
          </div>
        </SuperDataProvider>
      </body>
    </html>
  );
}
